services: 
  mysqldb:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/containers/
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb 
      MYSQL_USER: admin 
      MYSQL_PASSWORD: letadmin 
      MYSQL_ROOT_PASSWORD: letmein 
      SERVICES_TAGS: dev
      SERVICES_NAME: mysqldb
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge
